Update postman.yml

diff --git a/.github/workflows/postman.yml b/.github/workflows/postman.yml
--- a/.github/workflows/postman.yml
+++ b/.github/workflows/postman.yml
@@ -9,8 +9,13 @@ jobs:
     - name: Install Node.js
       uses: actions/setup-node@v2
     - name: Install Newman
-      run: npm install -g newman
+      run: npm install -g newman newman-reporter-htmlextra
     - name: Run Postman collection
-      run: newman run myCollection.json || echo "Error Ocuured"
+      run: newman run myCollection.json -r htmlextra -o report.html || echo "Error Ocuured"
+    - name: Commit and push the changes
+      run: |
+        git add report.html
+        git commit -m "Add newman html report"
+        git push https://${{ secrets.PUSH_TOKEN }}@github.com/OWNER/REPO.git main
  
 
