Update postman.yml

diff --git a/.github/workflows/postman.yml b/.github/workflows/postman.yml
--- a/.github/workflows/postman.yml
+++ b/.github/workflows/postman.yml
@@ -11,7 +11,7 @@ jobs:
     - name: Install Newman
       run: npm install -g newman newman-reporter-htmlextra
     - name: Run Postman collection
-      run: newman run myCollection.json -r htmlextra -o report.html || echo "Error Ocuured"
+      run: newman run myCollection.json -r htmlextra --reporter-htmlextra-export report.html || echo "Error Ocuured"
     - name: Commit and push the changes
       run: |
         git add report.html
