Update postman.yml

diff --git a/.github/workflows/postman.yml b/.github/workflows/postman.yml
--- a/.github/workflows/postman.yml
+++ b/.github/workflows/postman.yml
@@ -11,14 +11,14 @@ jobs:
     - name: Install Newman
       run: npm install -g newman newman-reporter-htmlextra
     - name: Run Postman collection
-      run: newman run myCollection.json -r htmlextra --reporter-htmlextra-export report.html || echo "Error Ocuured"
+      run: newman run myCollection.json -r htmlextra --reporter-htmlextra-export index.html || echo "Error Ocuured"
     - name: Configure git user
       run: |
         git config user.email "yashk.ug19.cs@nitp.ac.in"
         git config user.name "Yash-Kr"
     - name: Commit and push the changes
       run: |
-        git add report.html
+        git add index.html
         git commit -m "Add newman html report"
         git push https://${{ secrets.PUSH_TOKEN }}@github.com/Yash-Kr/PostmanDemo main
  
